Repository ccasalme/Weaver, pull requests merged in 2025-04, with the labels that each got.

#39 Page/rules
  client/src/pages/Privacy.tsx
  client/src/pages/Rules.tsx
  client/src/pages/WeaverInfo.tsx
Labels: enhancement

#37 Page/privacy
  client/src/pages/Privacy.tsx
Labels: enhancement

#41 Schema adjustments
  server/src/models/user.ts
  server/src/schemas/resolvers.ts
  server/src/schemas/typeDefs.ts
  server/src/seeds/userData.json
Labels: enhancement

#42 Cc/clientloginlogic2
  .gitignore
  client/src/assets/fallbackAvatar.png
  client/src/components/AddComment.tsx
  client/src/components/BranchStory.tsx
  client/src/components/CreateStory.tsx
  client/src/components/Footer.css
  client/src/components/Footer.tsx
  client/src/components/LikeButton.tsx
  client/src/components/Login.tsx
  client/src/components/OOPSModal.tsx
  client/src/data/dummyUser.json
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/index.css
  client/src/pages/Homepage.tsx
  client/src/pages/Profile.tsx
  client/src/pages/WeaverInfo.tsx
  client/src/pages/Wireframe.css
  client/src/utils/auth.ts
  client/vite.config.ts
  server/package.json
  server/src/utils/auth.ts
  tsconfig.json
Labels: bug, enhancement

#43 Page/architects
  client/src/pages/Architects.css
  client/src/pages/Architects.tsx
  server/src/schemas/resolvers.ts
  server/src/schemas/typeDefs.ts
Labels: enhancement

#44 some changes in the profile.tsx
  client/src/pages/Profile.tsx
Labels: bug, documentation, enhancement

#45 Adjust resolvers
  server/src/models/profile.ts
  server/src/schemas/resolvers.ts
  server/src/schemas/typeDefs.ts
  server/src/seeds/cleanDB.ts
  server/src/seeds/promptData.json
  server/src/server.ts
Labels: enhancement

#46 Testing branch
  server/src/schemas/resolvers.ts
  server/src/schemas/typeDefs.ts
Labels: bug

#47 Cc/profiletsx
  client/package-lock.json
  client/package.json
  client/src/components/AddComment.tsx
  client/src/components/BranchStory.tsx
  client/src/components/CollapsibleSection.tsx
  client/src/components/CreateStory.tsx
  client/src/components/DeleteStoryModal.tsx
  client/src/components/JoinUs.tsx
  client/src/components/LikeButton.tsx
  client/src/components/Login.tsx
  client/src/components/Navbar.tsx
  client/src/data/dummyUser.json
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/main.tsx
  client/src/pages/Architects.tsx
  client/src/pages/Homepage.tsx
  client/src/pages/Privacy.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Rules.tsx
  client/src/pages/WeaverInfo.tsx
  client/src/pages/Wireframe.css
  client/src/types/Profile.ts
  client/src/utils/apolloClient.ts
  client/src/utils/auth.ts
  server/src/schemas/resolvers.ts
  server/src/schemas/typeDefs.ts
  server/src/utils/auth.ts
Labels: enhancement

#48 Refactor server.ts to use fileURLToPath and dirname
  server/src/server.ts
Labels: enhancement

#49 Created yml file
  .github/workflows/render.deploy.yml
  package-lock.json
  package.json
Labels: enhancement

#52 img
  client/src/components/Navbar.css
  client/src/pages/Wireframe.css
Labels: enhancement

#53 img spelling mistake
  client/src/components/Modal.css
  client/src/pages/Wireframe.css
Labels: enhancement

#55 fixed bugs and took out the see threads on profile for now
  client/src/pages/Profile.tsx
Labels: documentation, enhancement

#57 Module/vitest
  client/package-lock.json
  client/package.json
  client/src/components/AddComment.test.tsx
  client/src/components/AddComment.tsx
  client/src/components/BranchStory.test.tsx
  client/src/components/CollapsibleSection.test.tsx
  client/src/components/CreateStory.test.tsx
  client/src/components/DeleteStoryModal.test.tsx
  client/src/components/DeleteStoryModal.tsx
  client/src/components/Footer.test.tsx
  client/src/components/JoinUs.test.tsx
  client/src/components/LikeButton.test.tsx
  client/src/components/Login.test.tsx
  client/src/components/Navbar.test.tsx
  client/src/setupTests.ts
  client/vite.config.ts
  package-lock.json
  package.json
Labels: enhancement

#58 added favicon and put back the styles for delete and addcomment
  client/index.html
  client/public/favicon.png
  client/src/components/AddComment.tsx
  client/src/components/DeleteStoryModal.tsx
Labels: enhancement
