Repository ccasalme/Weaver, pull requests merged in 2025-03, with the labels that each got.

#1 fixed server
  server/package.json
  server/src/config/connection.ts
Labels: documentation, good first issue

#2 readme instructions
  README.md
Labels: documentation

#3 Cc/readme
  README.md
Labels: documentation

#4 git instructions added
  README.md
Labels: documentation

#5 added apollo on client side
  client/package-lock.json
  client/package.json
Labels: documentation

#23 Cc/client
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/Footer.css
  client/src/components/Footer.tsx
  client/src/components/Navbar.css
  client/src/components/Navbar.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/pages/Architects.tsx
  client/src/pages/Error.tsx
  client/src/pages/Homepage.tsx
  client/src/pages/Privacy.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Rules.tsx
  client/src/pages/WeaverInfo.tsx
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: enhancement, good first issue

#24 typo fixed on the name of Navbar
  client/src/App.tsx
Labels: bug

#25 Cc/client enhance
  client/src/components/Footer.tsx
  client/src/components/Navbar.css
  client/src/components/Navbar.tsx
  client/src/index.css
Labels: enhancement

#26 Feature/modals
  client/src/App.tsx
  client/src/components/AuthModal.tsx
  client/src/components/ModalButton.tsx
Labels: enhancement

#27 Snabaj/models
  server/package.json
  server/src/models/comment.ts
  server/src/models/profile.ts
  server/src/models/prompt.ts
  server/src/models/story.ts
  server/src/models/user.ts
  server/src/models/vote.ts
  server/src/routes/api/index.ts
  server/src/routes/auth.ts
  server/src/routes/index.ts
  server/src/routes/protected.ts
  server/src/server.ts
Labels: enhancement, good first issue

#28 Cc/clientsetup
  client/index.html
  client/src/App.tsx
  client/src/components/CollapsibleSection.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Error.tsx
  client/src/pages/Privacy.css
  client/src/pages/Privacy.tsx
Labels: documentation, enhancement

#30 Graphql server
  client/package-lock.json
  client/vite.config.ts
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/middleware/authMiddleware.ts
  server/src/schemas/index.ts
  server/src/schemas/resolvers.ts
  server/src/schemas/typeDefs.ts
  server/src/server.ts
  server/src/utils/auth.ts
  server/tsconfig.json
  tsconfig.json
Labels: enhancement

#29 Cc/designstructure
  .gitignore
  client/src/assets/WireFrameBackground.png
  client/src/components/CollapsibleSection.tsx
  client/src/components/Footer.tsx
  client/src/components/Navbar.css
  client/src/components/Navbar.tsx
  client/src/index.css
  client/src/pages/Architects.tsx
  client/src/pages/Error.tsx
  client/src/pages/Homepage.tsx
  client/src/pages/Privacy.css
  client/src/pages/Privacy.tsx
  client/src/pages/Profile.tsx
  client/src/pages/WeaverInfo.tsx
  client/src/pages/Wireframe.css
Labels: enhancement

#31 Cc/clientlogin
  package-lock.json
  package.json
  server/package-lock.json
Labels: enhancement

#32 Cc/clientlogin
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/Homebannernotloggedin.png
  client/src/assets/weaverBanner.png
  client/src/components/AuthModal.tsx
  client/src/components/JoinUs.tsx
  client/src/components/Login.tsx
  client/src/components/Modal.css
  client/src/components/ModalButton.tsx
  client/src/components/Navbar.css
  client/src/components/Navbar.tsx
  client/src/data/dummyStories.json
  client/src/data/dummyUser.json
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/main.tsx
  client/src/pages/Homepage.tsx
  client/src/pages/Wireframe.css
  package-lock.json
  package.json
Labels: bug, documentation, enhancement

#33 Snabaj/schemas
  client/package-lock.json
  server/src/models/story.ts
  server/src/schemas/resolvers.ts
  server/src/schemas/typeDefs.ts
Labels: enhancement

#35 Cc/clientloginlogic
  client/src/assets/Homebannernotloggedin.png
  client/src/assets/PopupBackground.png
  client/src/assets/react.svg
  client/src/assets/storycardBackground.png
  client/src/assets/weaverBanner2.png
  client/src/components/JoinUs.tsx
  client/src/components/Login.tsx
  client/src/components/Modal.css
  client/src/components/Navbar.css
  client/src/components/Navbar.tsx
  client/src/index.css
  client/src/pages/Homepage.tsx
  client/src/pages/Wireframe.css
Labels: enhancement

#36 added Privacy Pol. in navbar
  client/src/components/Navbar.tsx
Labels: bug, enhancement
